
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: OSWALDO L. ZÁRATE ## put your name
title: 'INGENIERO ELECTRÓNICO | Desarrollador WEB Full Strack | Analista de Datos'  ## your title
location: La Paz , Bolivia


## Social Profiles
facebook: http://www.facebook.com/osvaldo.zarate.77  ## your facebook account url
twitter: http://www.twitter.com/walozarate  ## your twitter account url
linkedin: http://www.linkedin.com/in/ozarate  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
